# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WordCounterServiceStub(object):
    """Serviço A (Python)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CountWords = channel.unary_unary(
                '/textanalyzer.WordCounterService/CountWords',
                request_serializer=service__pb2.TextRequest.SerializeToString,
                response_deserializer=service__pb2.WordCountResponse.FromString,
                _registered_method=True)


class WordCounterServiceServicer(object):
    """Serviço A (Python)
    """

    def CountWords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WordCounterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CountWords': grpc.unary_unary_rpc_method_handler(
                    servicer.CountWords,
                    request_deserializer=service__pb2.TextRequest.FromString,
                    response_serializer=service__pb2.WordCountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'textanalyzer.WordCounterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('textanalyzer.WordCounterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WordCounterService(object):
    """Serviço A (Python)
    """

    @staticmethod
    def CountWords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/textanalyzer.WordCounterService/CountWords',
            service__pb2.TextRequest.SerializeToString,
            service__pb2.WordCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VowelCounterServiceStub(object):
    """Serviço B (Python)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CountVowels = channel.unary_unary(
                '/textanalyzer.VowelCounterService/CountVowels',
                request_serializer=service__pb2.TextRequest.SerializeToString,
                response_deserializer=service__pb2.VowelCountResponse.FromString,
                _registered_method=True)


class VowelCounterServiceServicer(object):
    """Serviço B (Python)
    """

    def CountVowels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VowelCounterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CountVowels': grpc.unary_unary_rpc_method_handler(
                    servicer.CountVowels,
                    request_deserializer=service__pb2.TextRequest.FromString,
                    response_serializer=service__pb2.VowelCountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'textanalyzer.VowelCounterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('textanalyzer.VowelCounterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VowelCounterService(object):
    """Serviço B (Python)
    """

    @staticmethod
    def CountVowels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/textanalyzer.VowelCounterService/CountVowels',
            service__pb2.TextRequest.SerializeToString,
            service__pb2.VowelCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
