// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto
#ifndef GRPC_service_2eproto__INCLUDED
#define GRPC_service_2eproto__INCLUDED

#include "service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace textanalyzer {

// Serviço A (C++)
class WordCounterService final {
 public:
  static constexpr char const* service_full_name() {
    return "textanalyzer.WordCounterService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CountWords(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::textanalyzer::WordCountResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::textanalyzer::WordCountResponse>> AsyncCountWords(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::textanalyzer::WordCountResponse>>(AsyncCountWordsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::textanalyzer::WordCountResponse>> PrepareAsyncCountWords(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::textanalyzer::WordCountResponse>>(PrepareAsyncCountWordsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CountWords(::grpc::ClientContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::WordCountResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CountWords(::grpc::ClientContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::WordCountResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::textanalyzer::WordCountResponse>* AsyncCountWordsRaw(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::textanalyzer::WordCountResponse>* PrepareAsyncCountWordsRaw(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CountWords(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::textanalyzer::WordCountResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::textanalyzer::WordCountResponse>> AsyncCountWords(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::textanalyzer::WordCountResponse>>(AsyncCountWordsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::textanalyzer::WordCountResponse>> PrepareAsyncCountWords(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::textanalyzer::WordCountResponse>>(PrepareAsyncCountWordsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CountWords(::grpc::ClientContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::WordCountResponse* response, std::function<void(::grpc::Status)>) override;
      void CountWords(::grpc::ClientContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::WordCountResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::textanalyzer::WordCountResponse>* AsyncCountWordsRaw(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::textanalyzer::WordCountResponse>* PrepareAsyncCountWordsRaw(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CountWords_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CountWords(::grpc::ServerContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::WordCountResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CountWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CountWords() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CountWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CountWords(::grpc::ServerContext* /*context*/, const ::textanalyzer::TextRequest* /*request*/, ::textanalyzer::WordCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCountWords(::grpc::ServerContext* context, ::textanalyzer::TextRequest* request, ::grpc::ServerAsyncResponseWriter< ::textanalyzer::WordCountResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CountWords<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CountWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CountWords() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::textanalyzer::TextRequest, ::textanalyzer::WordCountResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::WordCountResponse* response) { return this->CountWords(context, request, response); }));}
    void SetMessageAllocatorFor_CountWords(
        ::grpc::MessageAllocator< ::textanalyzer::TextRequest, ::textanalyzer::WordCountResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::textanalyzer::TextRequest, ::textanalyzer::WordCountResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CountWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CountWords(::grpc::ServerContext* /*context*/, const ::textanalyzer::TextRequest* /*request*/, ::textanalyzer::WordCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CountWords(
      ::grpc::CallbackServerContext* /*context*/, const ::textanalyzer::TextRequest* /*request*/, ::textanalyzer::WordCountResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CountWords<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CountWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CountWords() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CountWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CountWords(::grpc::ServerContext* /*context*/, const ::textanalyzer::TextRequest* /*request*/, ::textanalyzer::WordCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CountWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CountWords() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CountWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CountWords(::grpc::ServerContext* /*context*/, const ::textanalyzer::TextRequest* /*request*/, ::textanalyzer::WordCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCountWords(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CountWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CountWords() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CountWords(context, request, response); }));
    }
    ~WithRawCallbackMethod_CountWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CountWords(::grpc::ServerContext* /*context*/, const ::textanalyzer::TextRequest* /*request*/, ::textanalyzer::WordCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CountWords(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CountWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CountWords() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::textanalyzer::TextRequest, ::textanalyzer::WordCountResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::textanalyzer::TextRequest, ::textanalyzer::WordCountResponse>* streamer) {
                       return this->StreamedCountWords(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CountWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CountWords(::grpc::ServerContext* /*context*/, const ::textanalyzer::TextRequest* /*request*/, ::textanalyzer::WordCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCountWords(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::textanalyzer::TextRequest,::textanalyzer::WordCountResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CountWords<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CountWords<Service > StreamedService;
};

// Serviço B (Python)
class VowelCounterService final {
 public:
  static constexpr char const* service_full_name() {
    return "textanalyzer.VowelCounterService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CountVowels(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::textanalyzer::VowelCountResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::textanalyzer::VowelCountResponse>> AsyncCountVowels(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::textanalyzer::VowelCountResponse>>(AsyncCountVowelsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::textanalyzer::VowelCountResponse>> PrepareAsyncCountVowels(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::textanalyzer::VowelCountResponse>>(PrepareAsyncCountVowelsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CountVowels(::grpc::ClientContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::VowelCountResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CountVowels(::grpc::ClientContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::VowelCountResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::textanalyzer::VowelCountResponse>* AsyncCountVowelsRaw(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::textanalyzer::VowelCountResponse>* PrepareAsyncCountVowelsRaw(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CountVowels(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::textanalyzer::VowelCountResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::textanalyzer::VowelCountResponse>> AsyncCountVowels(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::textanalyzer::VowelCountResponse>>(AsyncCountVowelsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::textanalyzer::VowelCountResponse>> PrepareAsyncCountVowels(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::textanalyzer::VowelCountResponse>>(PrepareAsyncCountVowelsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CountVowels(::grpc::ClientContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::VowelCountResponse* response, std::function<void(::grpc::Status)>) override;
      void CountVowels(::grpc::ClientContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::VowelCountResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::textanalyzer::VowelCountResponse>* AsyncCountVowelsRaw(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::textanalyzer::VowelCountResponse>* PrepareAsyncCountVowelsRaw(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CountVowels_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CountVowels(::grpc::ServerContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::VowelCountResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CountVowels : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CountVowels() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CountVowels() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CountVowels(::grpc::ServerContext* /*context*/, const ::textanalyzer::TextRequest* /*request*/, ::textanalyzer::VowelCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCountVowels(::grpc::ServerContext* context, ::textanalyzer::TextRequest* request, ::grpc::ServerAsyncResponseWriter< ::textanalyzer::VowelCountResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CountVowels<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CountVowels : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CountVowels() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::textanalyzer::TextRequest, ::textanalyzer::VowelCountResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::VowelCountResponse* response) { return this->CountVowels(context, request, response); }));}
    void SetMessageAllocatorFor_CountVowels(
        ::grpc::MessageAllocator< ::textanalyzer::TextRequest, ::textanalyzer::VowelCountResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::textanalyzer::TextRequest, ::textanalyzer::VowelCountResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CountVowels() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CountVowels(::grpc::ServerContext* /*context*/, const ::textanalyzer::TextRequest* /*request*/, ::textanalyzer::VowelCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CountVowels(
      ::grpc::CallbackServerContext* /*context*/, const ::textanalyzer::TextRequest* /*request*/, ::textanalyzer::VowelCountResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CountVowels<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CountVowels : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CountVowels() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CountVowels() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CountVowels(::grpc::ServerContext* /*context*/, const ::textanalyzer::TextRequest* /*request*/, ::textanalyzer::VowelCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CountVowels : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CountVowels() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CountVowels() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CountVowels(::grpc::ServerContext* /*context*/, const ::textanalyzer::TextRequest* /*request*/, ::textanalyzer::VowelCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCountVowels(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CountVowels : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CountVowels() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CountVowels(context, request, response); }));
    }
    ~WithRawCallbackMethod_CountVowels() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CountVowels(::grpc::ServerContext* /*context*/, const ::textanalyzer::TextRequest* /*request*/, ::textanalyzer::VowelCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CountVowels(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CountVowels : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CountVowels() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::textanalyzer::TextRequest, ::textanalyzer::VowelCountResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::textanalyzer::TextRequest, ::textanalyzer::VowelCountResponse>* streamer) {
                       return this->StreamedCountVowels(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CountVowels() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CountVowels(::grpc::ServerContext* /*context*/, const ::textanalyzer::TextRequest* /*request*/, ::textanalyzer::VowelCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCountVowels(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::textanalyzer::TextRequest,::textanalyzer::VowelCountResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CountVowels<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CountVowels<Service > StreamedService;
};

}  // namespace textanalyzer


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_service_2eproto__INCLUDED
