// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto

#include "service.pb.h"
#include "service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace textanalyzer {

static const char* WordCounterService_method_names[] = {
  "/textanalyzer.WordCounterService/CountWords",
};

std::unique_ptr< WordCounterService::Stub> WordCounterService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WordCounterService::Stub> stub(new WordCounterService::Stub(channel, options));
  return stub;
}

WordCounterService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CountWords_(WordCounterService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WordCounterService::Stub::CountWords(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::textanalyzer::WordCountResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::textanalyzer::TextRequest, ::textanalyzer::WordCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CountWords_, context, request, response);
}

void WordCounterService::Stub::async::CountWords(::grpc::ClientContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::WordCountResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::textanalyzer::TextRequest, ::textanalyzer::WordCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CountWords_, context, request, response, std::move(f));
}

void WordCounterService::Stub::async::CountWords(::grpc::ClientContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::WordCountResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CountWords_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::textanalyzer::WordCountResponse>* WordCounterService::Stub::PrepareAsyncCountWordsRaw(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::textanalyzer::WordCountResponse, ::textanalyzer::TextRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CountWords_, context, request);
}

::grpc::ClientAsyncResponseReader< ::textanalyzer::WordCountResponse>* WordCounterService::Stub::AsyncCountWordsRaw(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCountWordsRaw(context, request, cq);
  result->StartCall();
  return result;
}

WordCounterService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WordCounterService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WordCounterService::Service, ::textanalyzer::TextRequest, ::textanalyzer::WordCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WordCounterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::textanalyzer::TextRequest* req,
             ::textanalyzer::WordCountResponse* resp) {
               return service->CountWords(ctx, req, resp);
             }, this)));
}

WordCounterService::Service::~Service() {
}

::grpc::Status WordCounterService::Service::CountWords(::grpc::ServerContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::WordCountResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* VowelCounterService_method_names[] = {
  "/textanalyzer.VowelCounterService/CountVowels",
};

std::unique_ptr< VowelCounterService::Stub> VowelCounterService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VowelCounterService::Stub> stub(new VowelCounterService::Stub(channel, options));
  return stub;
}

VowelCounterService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CountVowels_(VowelCounterService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VowelCounterService::Stub::CountVowels(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::textanalyzer::VowelCountResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::textanalyzer::TextRequest, ::textanalyzer::VowelCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CountVowels_, context, request, response);
}

void VowelCounterService::Stub::async::CountVowels(::grpc::ClientContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::VowelCountResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::textanalyzer::TextRequest, ::textanalyzer::VowelCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CountVowels_, context, request, response, std::move(f));
}

void VowelCounterService::Stub::async::CountVowels(::grpc::ClientContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::VowelCountResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CountVowels_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::textanalyzer::VowelCountResponse>* VowelCounterService::Stub::PrepareAsyncCountVowelsRaw(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::textanalyzer::VowelCountResponse, ::textanalyzer::TextRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CountVowels_, context, request);
}

::grpc::ClientAsyncResponseReader< ::textanalyzer::VowelCountResponse>* VowelCounterService::Stub::AsyncCountVowelsRaw(::grpc::ClientContext* context, const ::textanalyzer::TextRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCountVowelsRaw(context, request, cq);
  result->StartCall();
  return result;
}

VowelCounterService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VowelCounterService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VowelCounterService::Service, ::textanalyzer::TextRequest, ::textanalyzer::VowelCountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VowelCounterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::textanalyzer::TextRequest* req,
             ::textanalyzer::VowelCountResponse* resp) {
               return service->CountVowels(ctx, req, resp);
             }, this)));
}

VowelCounterService::Service::~Service() {
}

::grpc::Status VowelCounterService::Service::CountVowels(::grpc::ServerContext* context, const ::textanalyzer::TextRequest* request, ::textanalyzer::VowelCountResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace textanalyzer
#include <grpcpp/ports_undef.inc>

