# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0ctextanalyzer\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\'\n\x11WordCountResponse\x12\x12\n\nword_count\x18\x01 \x01(\x05\")\n\x12VowelCountResponse\x12\x13\n\x0bvowel_count\x18\x01 \x01(\x05\x32^\n\x12WordCounterService\x12H\n\nCountWords\x12\x19.textanalyzer.TextRequest\x1a\x1f.textanalyzer.WordCountResponse2a\n\x13VowelCounterService\x12J\n\x0b\x43ountVowels\x12\x19.textanalyzer.TextRequest\x1a .textanalyzer.VowelCountResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=31
  _globals['_TEXTREQUEST']._serialized_end=58
  _globals['_WORDCOUNTRESPONSE']._serialized_start=60
  _globals['_WORDCOUNTRESPONSE']._serialized_end=99
  _globals['_VOWELCOUNTRESPONSE']._serialized_start=101
  _globals['_VOWELCOUNTRESPONSE']._serialized_end=142
  _globals['_WORDCOUNTERSERVICE']._serialized_start=144
  _globals['_WORDCOUNTERSERVICE']._serialized_end=238
  _globals['_VOWELCOUNTERSERVICE']._serialized_start=240
  _globals['_VOWELCOUNTERSERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
